# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================
spring:
    application:
        name: spring-boot-rest-api-example
    datasource:
        url: jdbc:h2:file:./target/h2db/db/example;DB_CLOSE_DELAY=-1
        username: sa
        password:
    h2:
        console:
            enabled: true
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        database: H2
        hibernate:
            ddl-auto: none

server:
    port: 9000
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
        min-response-size: 1024

liquibase:
    change-log: classpath:liquibase/master.xml

# ===================================================================
# Application specific properties
# Add your own application properties here
# ===================================================================

application:
    security:
        authentication:
            jwt:
                secret: my-secret-token-to-change-in-production
                # Token is valid 24 hours
                token-validity-in-seconds: 86400
                token-validity-in-seconds-for-remember-me: 2592000